sudo: required
language: go
go_import_path: github.com/orange-cloudfoundry/githubrelease_exporter
services:
- docker
jobs:
  include:
  - stage: Build docker image
    env:
      - DOCKER_IMAGE_NAME=orangeopensource/githubrelease-exporter
      - secure: "qkcz9MsN1OkxTXZJ151hZgMgydT04Az+YLa2fF4DwxcQTsGsOgI82molcXUHx5g8undHSMOIzUFhT3QSl8+uH0QObTNcdkI222KtBII/MHw2gEemWEmgPkViJC+7p7a7mTunMOxk2hcKhHdQV1LQsjaomS9nW1hIsWE6yZYsxsQvOCnbMsanL3m0/J/0yoDTFs32gegiieIBEejuHa0oaHPe08bYV9V6854J+YyvfjFS0pkSqcMa7NS7oqS3cipflHbn2uIctNg/W/LPzIVRRB+9CgyXUzW0H+RWxStm/2OEOHThimpNlK3QzVXFAfSRgaQvzt9c2GVfkt/f6ysKFxS+gIwhezqSkVUifGsgfHTHx+x3uQWy9anLu9dnkSb3+AXKhahCOsVkzUMpzwrH8C5+vMeb920bJf1PMh9Mb57eQlyAuqr/9zMWeShr4xJl1zU8IQ+7KA3Zg3sieFixjUvTzCTK9PANNHS5D1JAbeQWsr6Vn1YSZ3Dvst3XmaHZai/2FfQxR1/LaBonnr2sQTnpAf1ejsXHDQBiLU9MEsX3dJKJ++JfQhdmjVj6FSoZh2I9CpyjiMIZGcSWWmLKTIx1dhQlT4ihwzx3qRFqzLzY2qukfqQ9cO2jEh9VYNdZPPGDgEQOZLNFnCq9ZfPZT11LJXo7NDMwVkTdCC3xVTs="
      - secure: "Kpsmd3vymnlwFS50sznLiq/ELXbRg5xUle97V3bjQ+uYyl9q15xDehsiyWPXhFzhiQN6+aEtmZbAEQz+UqGCudTgO1B+7IrT6VbwRPHTwmuXHU4nt3SbV/nFIhyGh99rS8MajhzaADxqjt2PZRX6WU5r+400kMe2ll9aa9niQT3rdJ9FkQLGzYTL7EwnxXJM3c1WAjDFZ+YuDmUU3SYhIHEWojxhN1WkkjCROv+eLDXAKF5G5u2ifLBNYl8FuP6t1wUaRfae8QekLubECtHIgwvIBbDkA3+s37WMZfK+rQs2jn9+Qrg2MD4cJHVqB1wiQggYUt5wzaiKGTmupq0gN6eIQmYer1Klio9Pix2iEGl7LYwYFUXE5C4T42/RgVsR2sKQ3xdInOU976V6+dHWWjo3tWJQwlMxLarw2g/yhyQlVtpxyUEF50o7MAaY/uaYYf6yCC9j8wK3iE8NnFXcwU/dyf8aEED01p9Ci10RR1S6xKUoDp9nGTDn63XvwIsS7uLTKyFVwZ1iyhIklTn8ycz+f03lrsz+ln5hOU6+Ijius6QM4KRJTez6EgNQj4sxYwqrpL9yFbQSQgEbS2VCPGw1JLo/UMH9wPjoUwiMVOzYGxatDqua7+vLwvOONHvMHTRSIp8FcsqNXbGgv2QYHSBx1f6CczhpLOWWlvhlxlw="
    script:
    - make crossbuild
    - ln -s .build/linux-amd64/githubrelease_exporter githubrelease_exporter
    - |
      if [ -n "$TRAVIS_TAG" ]; then
        make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
      else
        make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
      fi
    - |
      if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
        docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
      fi
    - docker images
    - |
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        docker push $DOCKER_IMAGE_NAME
      fi


